### ISSUE TITLE
rstiefel::rmf.matrix will throw warning "bessel_i(27.55,nu=398.5): precision lost in result"

### ISSUE THREAD

**Issue by MatthieuStigler** [pdhoff/rstiefel#1]
Hi

Thanks a lot for sharing the rstiefel package! I was interested in using it to simulate random orthogonal matrices, using function `rmf.matrix`. I notice that for a certain size of matrix, a warning arises: 

> warning messages:
> 1: In besselI(xn, 0.5 * (m - j - 1), expon.scaled = TRUE) :   bessel_i(27.55,nu=398.5): precision lost in result

Do you see any issue with this warning that I should take seriously? Or can I safely proceed?

Thanks!!

``` r
library(rstiefel)

N <- 800
p <-  2
out <- rstiefel::rmf.matrix(matrix(rnorm(N*p),N,p))
#> Warning in besselI(xn, 0.5 * (m - j - 1), expon.scaled = TRUE):
#> bessel_i(27.595,nu=398.5): precision lost in result
#> Warning in besselI(xd, 0.5 * (m - j - 1), expon.scaled = TRUE):
#> bessel_i(27.5984,nu=398.5): precision lost in result
```

<sup>Created on 2021-03-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by pdhoff** [comment]
The rejection sampler uses the `besselI` function in R which is an approximation to the real Bessel function. For certain matrix dimensions and concentration parameter values, the approximation is poor, and this warning is the result. I expect that when the approximation is poor, the accuracy of the sampler is reduced, but I do not have any quantitative details on this. 


-
Peter Hoff
Professor and Director of Graduate Studies
Department of Statistical Science
Duke University
