### ISSUE TITLE
"rWc" not resolved from current namespace

### ISSUE THREAD

**Issue by j-g-b** [pdhoff/rstiefel#2]
Hello,

Just a heads up: I was getting the error referenced in the title when running functions that relied on calls to underlying C functions in the rstiefel package. Substituting

`.C("rWc",PACKAGE="rstiefel", kap=as.double(kap), ...` for `.C("rWc", kap=as.double(kap), ...`

in line 26 of the file rW.R seemed to solve the problem. Similar substitutions in ry_bing.R and ry_bmf.R solved the other namespace issues.

**Comment by pdhoff** [comment]
The namespace issue arises when these functions are used inside other functions. 
I've updated the code so that this namespace issue should be resolved.
